Add new functions for junos modules (lock, unlock, load)
Juniper/salt pull request #26
Opened 2017-04-11 11:55 UTC by rajvidhimar

### What does this PR do?
* Add new functions - lock, load and unlock
* Update install_config to lock database before installing config.
* Minor changes in documentation

### What issues does this PR fix or reference?
NA

### Previous Behavior
install_config did not lock configuration before loading the new one.

### New Behavior
Now, install_config locks the configuration first.

### Tests written?
No

2017-04-11 16:15 UTC, vnitinv commented on salt/states/junos.py
> +        * name:
https://github.com/Juniper/salt/pull/26/files#diff-442286d51776ddefc791bc7f15e42fc2R272
&
https://github.com/Juniper/salt/pull/26/files#diff-442286d51776ddefc791bc7f15e42fc2R282

uses path and template_path, then we have removed this description and replaced it with name

2017-04-11 16:16 UTC, vnitinv reviewed
check my comment

2017-04-11 17:29 UTC, rajvidhimar commented on salt/states/junos.py
> +        * name:
We are using the name only..the earlier documentation was not correct.

2017-04-11 20:28 UTC, stacywsmith requested changes
Everything you have looks good, but don't we also need to implement a commit_check() method in order to implement the workflow we've been discussing?

2017-04-11 20:28 UTC, stacywsmith commented on salt/modules/junos.py
> +        configuration too.
Not only must the user call unlock, they should make sure they call unlock in the same orchestration run in which the lock was called.

2017-04-12 07:07 UTC, vnitinv approved these changes

2017-04-12 07:08 UTC, merged